const WINDOW_WIDTH = 640;
const WINDOW_HEIGHT = 640;

const HISTORY_BOX_W = WINDOW_WIDTH*6/10
const HISTORY_BOX_X = WINDOW_WIDTH*5/10 - HISTORY_BOX_W/2
const HISTORY_BOX_H = WINDOW_HEIGHT*6/10
const HISTORY_BOX_Y = WINDOW_HEIGHT*4/10 - HISTORY_BOX_H/2
const HISTORY_BOX_FONTSIZE = 24

const INPUT_BOX_X = WINDOW_WIDTH *5/10;
const INPUT_BOX_Y = WINDOW_HEIGHT*9/10;

const WORD_FONTSIZE = HISTORY_BOX_FONTSIZE
const PREV_WORD_X = WINDOW_WIDTH *2/10;
const PREV_WORD_Y = WINDOW_HEIGHT*8/10;
const SCORE_X = WINDOW_WIDTH*5/10;
const SCORE_Y = PREV_WORD_Y;
const GOAL_WORD_X = WINDOW_WIDTH *8/10;
const GOAL_WORD_Y = PREV_WORD_Y;

const SOUND_TOGGLE_X = WINDOW_WIDTH * 8.8/10
const SOUND_TOGGLE_Y = WINDOW_WIDTH * 9.5/10

const RESET_X = WINDOW_WIDTH * 1/10
const RESET_Y = WINDOW_WIDTH * 9.5/10

const RESTART_X = WINDOW_WIDTH * 4/10
const RESTART_Y = WINDOW_WIDTH * 9.5/10
